# Generated by Django 4.1.7 on 2023-04-04 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_rename_vatiente_categoria_variante_variante_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='Numero de orden')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('addres_line_1', models.CharField(max_length=100, verbose_name='Direccion')),
                ('addres_line_2', models.CharField(max_length=100, verbose_name='Direccion_2')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('order_note', models.CharField(blank=True, max_length=150, verbose_name='Descripcion o referencia')),
                ('order_total', models.FloatField(verbose_name='Total')),
                ('tax', models.FloatField(verbose_name='IVA')),
                ('status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Aceptado', 'Aceptado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Nuevo', max_length=20, verbose_name='Status')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='Ip')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Ya ordenado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de compra',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='Pago_id')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Metodo de pago')),
                ('amount_id', models.CharField(max_length=100, verbose_name='Monto a pagar')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('size', models.CharField(max_length=50, verbose_name='Talla')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('product_price', models.FloatField(verbose_name='Precio')),
                ('ordered', models.BooleanField(default=False, verbose_name='Ya ordenado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.order', verbose_name='Orden')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.payment', verbose_name='Pago')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.variante', verbose_name='Variante')),
            ],
            options={
                'verbose_name_plural': 'Productos en ordenes',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pyment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.payment', verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
