# Generated by Django 4.1.7 on 2023-04-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_remove_orderproduct_color_remove_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credito', 'Credito'), ('Contado', 'Contado'), ('Paypal', 'Paypal'), ('Tarjeta', 'Tarjeta')], default='Contado', max_length=100, verbose_name='Metodo de pago'),
        ),
    ]
