# Generated by Django 4.1.7 on 2023-04-06 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100, verbose_name='Direccion 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Direccion 2')),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile', verbose_name='Imagen de perfil')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Pais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Perfil de usuario',
            },
        ),
    ]
