# Generated by Django 4.1.7 on 2023-03-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_variante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variante',
            old_name='vatiente_categoria',
            new_name='variante_categoria',
        ),
    ]
