# Generated by Django 4.1.7 on 2023-03-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('imagen', models.ImageField(blank=True, upload_to='fotos/categorias', verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
